In [3]:
import numpy as np

In [4]:
my_list = [1,2,3,4]

In [5]:
my_arr = np.array(my_list)

In [6]:
print(my_arr)

[1 2 3 4]


In [7]:
print(type(my_arr))

<class 'numpy.ndarray'>


In [8]:
my_matrix = [(1,2,5),(3,5,3),(4,3,2)]

In [9]:
print(my_matrix)

[(1, 2, 5), (3, 5, 3), (4, 3, 2)]


In [10]:
arr_matrix = np.array(my_matrix)
print(arr_matrix)

[[1 2 5]
 [3 5 3]
 [4 3 2]]


In [12]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])